services:
  init:
    image: docker.io/billos/broadcastarr:latest
    command: "init"
    env_file:
      - .env
      - .env.init
    environment:
      NODE_ENV: development
      LOG_LEVEL: 2
      MONGO_URL: mongodb://mongo:27017
      MONGO_AGENDA_DB: agenda
      MONGO_DB: broadcastarr
      DATA_FOLDER: /data
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped
    volumes:
      - ./data:/data
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: docker.io/library/mongo:7.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - broadcastarr_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  broadcastarr_data:
    external: true
