services:
  server:
    image: docker.io/billos/broadcastarr:1.2.3
    container_name: server
    command: "dev:server"
    volumes:
      - ./src:/app/src
      - ${M3U8_FOLDER}:${M3U8_FOLDER}:rw
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
    env_file:
      - .env
      - .env.dev
    environment:
      NODE_ENV: development
      LOG_LEVEL: 2
      MONGO_URL: mongodb://mongo
      MONGO_AGENDA_DB: agenda
      MONGO_DB: broadcastarr
    deploy:
      resources:
        limits:
          memory: 4g
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  worker:
    extends:
      service: server
    container_name: worker
    command: "dev:worker"

  mongo:
    image: docker.io/library/mongo:7.0
    container_name: mongo
    restart: unless-stopped
    volumes:
      - broadcastarr_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  broadcastarr_data:
    external: true
